apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
data:
  MONGODB_USERNAME: {{ toJson .Values.mongodb.auth.usernames | b64enc | quote }}
  MONGODB_PASSWORD: {{ toJson .Values.mongodb.auth.passwords | b64enc | quote }}